name: Bump Version and Publish Docker Image

on:
  push:
    branches:
      - main  # Runs on pushes to the main branch
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Poetry
        run: |
          pip install poetry
          poetry install
      - name: Install bump2version
        run: |
          pip install bump2version
      - name: Bump Version
        id: bumpversion
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          bump2version patch  # You can change this to minor or major
          git push --follow-tags

  build_and_push:
    runs-on: ubuntu-latest
    needs: bump_version  # Wait for the version bump job to finish
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: |
            ghcr.io/ELIXIR-NO/pipeline-heartbeat:${{ github.ref_name }}  # Image tagged with Git ref
            ghcr.io/ELIXIR-NO/pipeline-heartbeat:latest  # Always update 'latest'
